"""Format ReviewFinding and PRSummary objects into Markdown comments."""

from __future__ import annotations

from pr_reviewer.models import PRSummary, ReviewFinding, Severity, TestStub

# Severity emoji mapping
_SEV_EMOJI = {
    Severity.CRITICAL: "🚨",
    Severity.HIGH: "🔴",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "ℹ️",
}

_RISK_EMOJI = {
    Severity.CRITICAL: "🔥",
    Severity.HIGH: "🔴",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
    Severity.INFO: "✅",
}


def format_inline_comment(finding: ReviewFinding) -> str:
    """Format a ReviewFinding as an inline PR comment body (Markdown)."""
    emoji = _SEV_EMOJI.get(finding.severity, "")
    header = f"{emoji} **{finding.severity.value}** [{finding.category.value}]"

    parts = [header, "", finding.message]

    if finding.suggestion:
        parts += [
            "",
            "**Suggestion:**",
            "```python",
            finding.suggestion,
            "```",
        ]

    confidence_pct = int(finding.confidence * 100)
    parts += ["", f"<sub>Confidence: {confidence_pct}% | 🤖 pr-reviewer</sub>"]

    return "\n".join(parts)


def format_summary_comment(summary: PRSummary, findings: list[ReviewFinding]) -> str:
    """Format a PRSummary + all findings into a top-level PR comment (Markdown)."""
    risk_emoji = _RISK_EMOJI.get(summary.risk_level, "")

    lines: list[str] = [
        "# 🤖 pr-reviewer — Code Review Summary",
        "",
        f"**Risk Level:** {risk_emoji} {summary.risk_level.value}",
        "",
        "## Overview",
        summary.overview,
        "",
    ]

    if summary.intent:
        lines += ["## PR Intent", summary.intent, ""]

    # Findings table
    lines += [
        "## Findings by Severity",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in Severity:
        count = summary.findings_by_severity.get(sev.value, 0)
        emoji = _SEV_EMOJI.get(sev, "")
        lines.append(f"| {emoji} {sev.value} | {count} |")
    lines.append("")

    # Key concerns
    if summary.key_concerns:
        lines += ["## Key Concerns", ""]
        for concern in summary.key_concerns:
            lines.append(f"- {concern}")
        lines.append("")

    # Detailed findings list
    if findings:
        lines += ["## All Findings", ""]
        for f in sorted(findings, key=lambda x: x.severity, reverse=True):
            emoji = _SEV_EMOJI.get(f.severity, "")
            lines.append(
                f"- {emoji} **{f.severity.value}** `{f.file}:{f.line_start}` "
                f"[{f.category.value}] — {f.message[:100]}"
            )
        lines.append("")

    # Test stubs
    if summary.test_stubs:
        lines += ["## Suggested Test Stubs", ""]
        for stub in summary.test_stubs:
            lines += [
                f"### `{stub.test_name}` — {stub.description}",
                "",
                f"*Source:* `{stub.source_file}`",
                "",
                "```python",
                stub.stub_code,
                "```",
                "",
            ]

    # General suggestions
    if summary.suggestions:
        lines += ["## General Suggestions", ""]
        for s in summary.suggestions:
            lines.append(f"- {s}")
        lines.append("")

    lines += [
        "---",
        "<sub>Generated by [pr-reviewer](https://github.com/your-org/pr-reviewer) "
        "powered by Claude</sub>",
    ]

    return "\n".join(lines)
